server:
  port: 8081
spring:
  application:
    name: taxi.hub
  messages:
    basename: messages
    encoding: utf-8
  liquibase:
    change-log: classpath:db/migrations/changeLog.xml
    url: jdbc:postgresql://localhost:5432/taxi-hub
    user: taxiHub
    password: root
    enabled: true

  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:postgresql://localhost:5432/taxi-hub
    username: taxiHub
    password: root
  data:
    redis:
      host: localhost
      port: 6379
      user-prefix: "user_state:"
      order-prefix: "order:"
      last-message-id-prefix: "last_message_id:"
      page-history-prefix: "page_history:"
      driver-route-prefix: "driver_route:"
      ttl-hours: 24

telegram:
  bot:
    token: "8396733420:AAHn1NIwpil9wgxD10ew-5XI_70JFTuiAA4"
    username: "MohirTaxiBot"
    oson-taxi-admin: "-1003322130715"

logging:
  level:
    liquibase: debug